# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "harshvardhan-terragrunt"
    key     = "./terraform.tfstate"
    profile = "harshvardhan"
    region  = "us-west-2"
  }
}
