name: Deploy Application

on:
  push:
    branches:
      - dev
      - main

jobs:
  SetEnvironment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{env.branch}}
    steps:
      - name: Set Environment
        id: set_environment
        run: echo "branch=dev" >> $GITHUB_ENV

      - name: Print
        run: echo ${{env.branch}}
  Deploy:
    runs-on: ubuntu-latest
    needs: SetEnvironment
    env:
      TF_VAR_environment: ${{ needs.SetEnvironment.outputs.environment }}
    steps:
      - name: Print env
        run: echo ${{env.TF_VAR_environment}}
