name: Dev Deploy

on:
  workflow_dispatch:
  push:
    branches: "dev"

jobs:
  Push:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/reusable_branch.yml
    with:
      apply: "true"
      environment: "dev"
      build: "false"
      infra: "true"

    secrets:
      RDS_USERNAME: ${{secrets.RDS_USERNAME}}
      RDS_PASSWORD: ${{secrets.RDS_PASSWORD}}
      AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
