name: Dev Deploy

on:
  workflow_dispatch:
  push:
    branches: "dev"

jobs:
  Push:
    uses: ./.github/workflows/reusable_branch.yml
    with:
      apply: "true"
      #   environment: "dev"
      build: "false"
      infra: "true"

    secrets:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      RDS_USERNAME: ${{secrets.RDS_USERNAME}}
      RDS_PASSWORD: ${{secrets.RDS_PASSWORD}}
      AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
