name: Deploy Application

on:
  push:
    branches:
      - dev
      - sandbox
      - main

jobs:
  Push:
    permissions:
      id-token: write
      contents: read

    uses: ./.github/workflows/reusable_cond.yml
    with:
      apply: "true"
      build: "true"
      infra: "false"

    secrets:
      RDS_USERNAME: ${{secrets.RDS_USERNAME}}
      RDS_PASSWORD: ${{secrets.RDS_PASSWORD}}
      AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
