name: Deploy Application

on:
  workflow_dispatch:
  # push:
  # branches:
  #   - dev
  #   - sandbox
  #   - main

jobs:
  Push:
    # For OIDC ROle.
    permissions:
      id-token: write
      contents: read

    uses: ./.github/workflows/reusable_cond.yml
    with:
      apply: "true"
      build: "true"
      infra: "true"

    secrets:
      RDS_USERNAME: ${{secrets.RDS_USERNAME}}
      RDS_PASSWORD: ${{secrets.RDS_PASSWORD}}
      AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
      OIDC_ROLE : ${{secrets.OIDC_ROLE}}
