name: Build and Plan
# ----------------------------------
# Optional File
# ----------------------------------

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      apply:
        required: true
        type: string
      build:
        required: true
        type: string
      infra:
        required: true
        type: string
    secrets:
      RDS_USERNAME:
        required: true
      RDS_PASSWORD:
        required: true
      AWS_ACCOUNT_ID:
        required: true

jobs:
  Build:
    if: ${{inputs.build == 'true' }}
    defaults:
      run:
        working-directory: ./auth

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NPM
        run: sudo apt update && sudo apt install npm

      - name: Install Packages
        run: npm install

      - name: Build app
        run: npm run build

  Deploy:
    permissions:
      id-token: write
      contents: read

    if: ${{inputs.infra == 'true' }}
    # needs: Build
    defaults:
      run:
        working-directory: ./Infrastructure
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}

    env:
      TF_VAR_environment: ${{inputs.environment}}
      TF_VAR_tag: ${{github.sha}}
      ECR_REPO: "${{inputs.environment}}-repo"
      TF_VAR_ecr_repo: "${{inputs.environment}}-repo"
      TF_VAR_profile: "harsh"
      TF_VAR_region: "us-west-2"
      TF_VAR_account_id: ${{secrets.AWS_ACCOUNT_ID}}
      TF_VAR_username: ${{secrets.RDS_USERNAME}}
      TF_VAR_password: ${{secrets.RDS_PASSWORD}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/OIDC_Connect
          # role-session-name: harsh
          aws-region: us-west-2

      - name: Get Identity
        run: aws sts get-caller-identity

      - name: Check if there's an ECR already
        id: ECR
        continue-on-error: true
        run: aws ecr describe-repositories --repository-names $TF_VAR_ecr_repo

      - name: Create ECR
        if: ${{steps.ECR.outcome != 'success'}}
        run: aws ecr create-repository --repository-name $TF_VAR_ecr_repo --region $TF_VAR_region

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: "${{inputs.environment}}-repo"
          IMAGE_TAG: ${{github.sha}}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG ../auth
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: install Terraform
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install terraform

      - name: initialize terraform
        run: terraform init

      - name: plan terraform
        run: terraform plan

      - name: Apply terraform
        if: ${{inputs.apply == 'true'}}
        run: terraform apply -auto-approve
