name: Deploy Application

on:
  push:
    branches: "dev"

jobs:
  Deploy:
    defaults:
      run:
        working-directory: ./Infrastructure
    runs-on: ubuntu-latest
    environment: dev

    env:
      ECR_REPO: "harshvardhan-repo"
      TF_VAR_ecr_repo: "harshvardhan-repo"
      TF_VAR_profile: "harsh"
      TF_VAR_region: "us-west-2"
      TF_VAR_account_id: ${{secrets.AWS_ACCOUNT_ID}}
      TF_VAR_username: ${{secrets.RDS_USERNAME}}
      TF_VAR_password: ${{secrets.RDS_PASSWORD}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: credentials on cli
        run: bash ../.github/workflows/commands.sh
        env:
          AWS_REGION: "us-west-2"
          AWS_PROFILE: "harsh"
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: harshvardhan-repo
          IMAGE_TAG: latest
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
